const SM_API="https://weekly-range-api.changowalu.workers.dev/smart-money";
const SM_UNIVERSE=["AAPL","NVDA","AMZN","GOOGL","META","AVGO","TSLA","AMD","NFLX","ORCL","CRM","ADBE","CSCO","QCOM","MU","AMAT","JPM","BAC","WFC","GS","V","MA","PYPL","COF","AXP","HOOD","LLY","UNH","JNJ","ABBV","MRK","PFE","TMO","ABT","WMT","COST","HD","LOW","MCD","NKE","KO","PEP","XOM","CVX","COP","SLB","CAT","DE","GE","HON","BA","RTX","UBER","PLTR","PANW","CRWD","NOW","SHOP","SPY","QQQ","IWM","DIA","XLF","XLK"];
function smEscape(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function smFmtMoney(v){v=Number(v)||0;return v>=1e9?"$"+(v/1e9).toFixed(2)+"B":v>=1e6?"$"+(v/1e6).toFixed(2)+"M":v>=1e3?"$"+(v/1e3).toFixed(1)+"K":"$"+v.toFixed(0);}
function smBadge(v){const x=String(v||"NEUTRAL").toUpperCase();const cls=x.includes("BUY")||x.includes("UP")||x.includes("BULL")||x.includes("EXPOSURE")||x.includes("HOLDING")?"green":x.includes("SELL")||x.includes("DOWN")||x.includes("BEAR")?"red":"yellow";return '<span class="'+cls+'"><b>'+smEscape(x)+'</b></span>';}
async function smLoad(){const input=document.getElementById("symbols");if(!input)return;const symbols=[...new Set(input.value.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean))].slice(0,20);const status=document.getElementById("smStatus"),rows=document.getElementById("smRows");status.textContent="Cargando SEC / institucionales / Congreso / actividad inusual…";rows.innerHTML='<tr><td colspan="12" class="loading">Consultando datos…</td></tr>';try{const r=await fetch(SM_API+"?symbols="+encodeURIComponent(symbols.join(",")),{cache:"no-store"}),d=await r.json();if(!r.ok||d.status!=="ok")throw Error(d.message||"Error Smart Money");rows.innerHTML=(d.data||[]).map((x,i)=>'<tr><td><b>'+(i+1)+'</b></td><td><b>'+smEscape(x.symbol)+'</b></td><td class="score '+(x.score>=70?"green":x.score<=30?"red":"yellow")+'">'+x.score+'</td><td>'+smBadge(x.insider.signal)+'<br><span class="small">'+x.insider.count+" eventos · "+smFmtMoney(x.insider.netValue)+'</span></td><td>'+smBadge(x.institutional.signal)+'<br><span class="small">'+x.institutional.filers+" managers</span></td><td>'+smBadge(x.congress.signal)+'<br><span class="small">'+x.congress.count+" transacciones</span></td><td>'+smBadge(x.unusual.signal)+'<br><span class="small">RVOL '+(Number(x.unusual.rvol||0)).toFixed(2)+"x · "+(Number(x.unusual.priceChange||0)).toFixed(1)+"%</span></td><td>'+smBadge(x.etf.signal)+'<br><span class="small">'+(x.etf.count||0)+" holdings</span></td><td>'+smBadge(x.options?.signal||"OFF")+'<br><span class="small">C/P '+(x.options?.callPutRatio==null?"—":Number(x.options.callPutRatio).toFixed(2)+"x")+'</span></td><td>'+smEscape(x.dataQuality)+'</td><td>'+smEscape(x.asOf||"")+'</td><td><button onclick="smDetails(\''+smEscape(x.symbol)+'\')">DETALLES</button></td></tr>').join("")||'<tr><td colspan="12">Sin datos.</td></tr>';status.textContent="Actualizado · "+(d.generatedAt||"")+" · Congreso "+(d.sources?.congress?"ON":"OFF")+" · ETF "+(d.sources?.etf?"ON":"OFF");}catch(e){status.textContent="Smart Money: "+e.message;rows.innerHTML='<tr><td colspan="12" class="red">No se pudo cargar Smart Money.</td></tr>';}}
async function smDetails(symbol){const status=document.getElementById("smStatus");status.textContent="Cargando detalles de "+symbol+"…";try{const r=await fetch(SM_API+"?symbol="+encodeURIComponent(symbol)+"&detail=1",{cache:"no-store"}),d=await r.json();if(!r.ok||d.status!=="ok")throw Error(d.message||"Error");const x=d.data?.[0]||d.data,p=document.getElementById("smDetail");p.classList.remove("hidden");const holdings=(x.etf?.holdings||[]).map(h=>'<tr><td>'+smEscape(h.symbol||"")+'</td><td>'+smEscape(h.name||"")+'</td><td>'+smEscape(h.weight==null?"":(Number(h.weight)*100).toFixed(2)+"%")+'</td></tr>').join("");p.innerHTML='<h3 class="section-title">'+smEscape(symbol)+' — Smart Money</h3><div class="summary"><span class="badge">Score: <b>'+x.score+'</b></span><span class="badge">Insiders: '+smBadge(x.insider.signal)+'</span><span class="badge">13F: '+smBadge(x.institutional.signal)+'</span><span class="badge">Congress: '+smBadge(x.congress.signal)+'</span><span class="badge">Unusual: '+smBadge(x.unusual.signal)+'</span><span class="badge">Opciones: '+smBadge(x.options?.signal||"OFF")+' · C/P '+(x.options?.callPutRatio==null?"—":Number(x.options.callPutRatio).toFixed(2)+"x")+'</span></div><p class="small">Actividad: '+smEscape(x.unusual.reason||"")+" · RVOL "+(Number(x.unusual.rvol||0)).toFixed(2)+"x · cambio 5D "+(Number(x.unusual.priceChange||0)).toFixed(2)+"%</p><div class=\"scroll\"><table><thead><tr><th>Fuente</th><th>Fecha</th><th>Tipo</th><th>Actor/Filer</th><th>Acción</th><th>Valor</th></tr></thead><tbody>"+(x.events||[]).map(e=>'<tr><td>'+smEscape(e.source)+'</td><td>'+smEscape(e.date)+'</td><td>'+smEscape(e.type)+'</td><td>'+smEscape(e.actor)+'</td><td>'+smEscape(e.action)+'</td><td>'+smEscape(e.value||"")+'</td></tr>').join("")+'</tbody></table></div><h4>ETF / exposición</h4><div class="scroll"><table><thead><tr><th>Símbolo</th><th>Holding</th><th>Peso</th></tr></thead><tbody>'+holdings+'</tbody></table></div><p class="small">Institucional: '+smEscape(x.institutional.note||"")+" · Congreso: "+smEscape(x.congress.note||"")+" · ETF: "+smEscape(x.etf.note||"")+'</p>';status.textContent="Detalle cargado.";}catch(e){status.textContent="Detalle: "+e.message;}}


async function smScanUniverse(){
  const status=document.getElementById("smStatus"),rows=document.getElementById("smRows"),b=document.getElementById("smUniverse");
  b.disabled=true; rows.innerHTML='<tr><td colspan="12" class="loading">Escaneando universo…</td></tr>';
  const all=[];
  try{
    for(let i=0;i<SM_UNIVERSE.length;i+=8){
      const batch=SM_UNIVERSE.slice(i,i+8);
      status.textContent="Smart Money universo · "+Math.min(i+8,SM_UNIVERSE.length)+"/"+SM_UNIVERSE.length;
      const r=await fetch(SM_API+"?symbols="+encodeURIComponent(batch.join(",")),{cache:"no-store"});
      const d=await r.json(); if(!r.ok||d.status!=="ok")throw Error(d.message||"Error");
      all.push(...(d.data||[]));
      document.getElementById("progressBar").style.width=(Math.min(i+8,SM_UNIVERSE.length)/SM_UNIVERSE.length*100)+"%";
      document.getElementById("progressText").textContent="Smart Money "+Math.min(i+8,SM_UNIVERSE.length)+"/"+SM_UNIVERSE.length;
      if(i+8<SM_UNIVERSE.length)await new Promise(x=>setTimeout(x,61000));
    }
    all.sort((a,b)=>b.score-a.score);
    rows.innerHTML=all.map((x,i)=>'<tr><td><b>'+(i+1)+'</b></td><td><b>'+smEscape(x.symbol)+'</b></td><td class="score '+(x.score>=70?"green":x.score<=30?"red":"yellow")+'">'+x.score+'</td><td>'+smBadge(x.insider.signal)+'<br><span class="small">'+x.insider.count+" eventos</span></td><td>"+smBadge(x.institutional.signal)+"<br><span class=\"small\">"+x.institutional.filers+" managers</span></td><td>"+smBadge(x.congress.signal)+"<br><span class=\"small\">"+x.congress.count+" transacciones</span></td><td>"+smBadge(x.unusual.signal)+"<br><span class=\"small\">RVOL "+(Number(x.unusual.rvol||0)).toFixed(2)+"x</span></td><td>"+smBadge(x.etf.signal)+"</td><td>"+smBadge(x.options?.signal||"OFF")+"<br><span class=\"small\">C/P "+(x.options?.callPutRatio==null?"—":Number(x.options.callPutRatio).toFixed(2)+"x")+"</span></td><td>"+smEscape(x.dataQuality)+"</td><td>"+smEscape(x.asOf||"")+"</td><td><button onclick="smDetails(\''+smEscape(x.symbol)+'\')">DETALLES</button></td></tr>').join("");
    status.textContent="Smart Money universo terminado · "+all.length+" símbolos";
  }catch(e){status.textContent="Smart Money: "+e.message;}
  finally{b.disabled=false;}
}
